from __future__ import annotations

from typing import Any


def profile_templates() -> list[dict[str, Any]]:
    """Built-in profile templates for quick create."""
    return [
        {
            "id": "clean",
            "name": {"zh": "纯净档案", "en": "Clean Profile"},
            "description": {
                "zh": "默认可见浏览器，拦截 WebRTC，适合日常隔离。",
                "en": "Visible browser with WebRTC blocked for everyday isolation.",
            },
            "profile": {
                "name": "Clean Profile",
                "startup_url": "https://browserleaks.com/javascript",
                "mode": "browser",
                "os": "auto",
                "headless": False,
                "persistent_context": True,
                "humanize": True,
                "geoip": False,
                "block_images": False,
                "block_webrtc": True,
                "block_webgl": False,
                "disable_coop": True,
                "enable_cache": True,
                "webrtc_mode": "disable",
                "canvas_noise": True,
                "audio_noise": True,
                "tags": ["template", "clean"],
                "notes": "Created from Clean template",
            },
        },
        {
            "id": "stealth-shop",
            "name": {"zh": "电商隔离", "en": "Shopping Isolation"},
            "description": {
                "zh": "持久化 + 人性化鼠标 + 禁用 WebRTC，适合多店铺。",
                "en": "Persistent + humanize + WebRTC off for multi-store work.",
            },
            "profile": {
                "name": "Shopping Profile",
                "startup_url": "about:blank",
                "mode": "browser",
                "os": "windows",
                "headless": False,
                "persistent_context": True,
                "humanize": True,
                "geoip": True,
                "block_images": False,
                "block_webrtc": True,
                "block_webgl": False,
                "disable_coop": True,
                "enable_cache": True,
                "webrtc_mode": "disable",
                "locale": "en-US",
                "timezone": "America/New_York",
                "tags": ["template", "shopping"],
                "notes": "Created from Shopping template",
            },
        },
        {
            "id": "automation-server",
            "name": {"zh": "自动化 Server", "en": "Automation Server"},
            "description": {
                "zh": "以 server 模式暴露 Playwright 端点，便于脚本连接。",
                "en": "Server mode exposing a Playwright endpoint for scripts.",
            },
            "profile": {
                "name": "Automation Server",
                "startup_url": "",
                "mode": "server",
                "os": "auto",
                "headless": True,
                "persistent_context": False,
                "humanize": False,
                "geoip": False,
                "block_images": False,
                "block_webrtc": True,
                "block_webgl": False,
                "disable_coop": True,
                "enable_cache": False,
                "webrtc_mode": "disable",
                "tags": ["template", "automation", "server"],
                "notes": "Created from Automation Server template",
            },
        },
        {
            "id": "headless-check",
            "name": {"zh": "无界面检测", "en": "Headless Check"},
            "description": {
                "zh": "无界面快速打开检测页，适合批量核验。",
                "en": "Headless launch to a fingerprint check page.",
            },
            "profile": {
                "name": "Headless Check",
                "startup_url": "https://browserleaks.com/javascript",
                "mode": "browser",
                "os": "auto",
                "headless": True,
                "persistent_context": False,
                "humanize": False,
                "geoip": False,
                "block_images": True,
                "block_webrtc": True,
                "block_webgl": False,
                "disable_coop": True,
                "enable_cache": False,
                "webrtc_mode": "disable",
                "tags": ["template", "headless"],
                "notes": "Created from Headless Check template",
            },
        },
    ]
